[package]
name = "vend-controller"
version = "0.1.0"
authors = ["hexane360 <colin@gilgenbach.net>"]
edition = "2018"

[dependencies]
num-derive = "^0.2"
num-traits = "^0.2"
crossbeam = "^0.6"
sysfs_gpio = "^0.5"
sysfs-pwm = "^0.1"
generic-array = "^0.13"
#compiler_builtins = "^0.1"
